## Container scan evidence CVE
<strong>Image name:</strong> registry.ente.regione.emr.it/parer/okd/verifica-firma-eidas:
<br/><strong>Run date:</strong> Mon Nov 13 16:12:08 CET 2023
<br/><strong>Produced by:</strong> <a href="https://gitlab.ente.regione.emr.it/parer/okd/verifica-firma-eidas/-/jobs/135789">Job</a>
<br/><strong>CVE founded:</strong> 9
| CVE | Description | Severity | Solution | 
|:---:|:---|:---:|:---|
| [CVE-2023-32360](https://access.redhat.com/errata/RHSA-2023:4838)|An authentication issue was addressed with improved state management. This issue is fixed in macOS Big Sur 11.7.7, macOS Monterey 12.6.6, macOS Ventura 13.4. An unauthenticated user may be able to access recently printed documents.|High|Upgrade cups-libs to 1:2.2.6-51.el8_8.1|
| [CVE-2023-4911](http://packetstormsecurity.com/files/174986/glibc-ld.so-Local-Privilege-Escalation.html)|A buffer overflow was discovered in the GNU C Library's dynamic loader ld.so while processing the GLIBC_TUNABLES environment variable. This issue could allow a local attacker to use maliciously crafted GLIBC_TUNABLES environment variables when launching binaries with SUID permission to execute code with elevated privileges.|High|Upgrade glibc to 2.28-225.el8_8.6|
| [CVE-2023-4911](http://packetstormsecurity.com/files/174986/glibc-ld.so-Local-Privilege-Escalation.html)|A buffer overflow was discovered in the GNU C Library's dynamic loader ld.so while processing the GLIBC_TUNABLES environment variable. This issue could allow a local attacker to use maliciously crafted GLIBC_TUNABLES environment variables when launching binaries with SUID permission to execute code with elevated privileges.|High|Upgrade glibc-common to 2.28-225.el8_8.6|
| [CVE-2023-4911](http://packetstormsecurity.com/files/174986/glibc-ld.so-Local-Privilege-Escalation.html)|A buffer overflow was discovered in the GNU C Library's dynamic loader ld.so while processing the GLIBC_TUNABLES environment variable. This issue could allow a local attacker to use maliciously crafted GLIBC_TUNABLES environment variables when launching binaries with SUID permission to execute code with elevated privileges.|High|Upgrade glibc-minimal-langpack to 2.28-225.el8_8.6|
| [CVE-2023-44487](http://www.openwall.com/lists/oss-security/2023/10/13/4)|The HTTP/2 protocol allows a denial of service (server resource consumption) because request cancellation can reset many streams quickly, as exploited in the wild in August through October 2023.|High|Upgrade libnghttp2 to 1.33.0-5.el8_8|
| [CVE-2023-24329](https://access.redhat.com/errata/RHSA-2023:3595)|An issue in the urllib.parse component of Python before 3.11.4 allows attackers to bypass blocklisting methods by supplying a URL that starts with blank characters.|High|Upgrade platform-python to 3.6.8-51.el8_8.1|
| [CVE-2023-40217](https://access.redhat.com/errata/RHSA-2023:5462)|An issue was discovered in Python before 3.8.18, 3.9.x before 3.9.18, 3.10.x before 3.10.13, and 3.11.x before 3.11.5. It primarily affects servers (such as HTTP servers) that use TLS client authentication. If a TLS server-side socket is created, receives data into the socket buffer, and then is closed quickly, there is a brief window where the SSLSocket instance will detect the socket as "not connected" and won't initiate a handshake, but buffered data will still be readable from the socket buffer. This data will not be authenticated if the server-side TLS peer is expecting client certificate authentication, and is indistinguishable from valid TLS stream data. Data is limited in size to the amount that will fit in the buffer. (The TLS connection cannot directly be used for data exfiltration because the vulnerable code path requires that the connection be closed on initialization of the SSLSocket.)|High|Upgrade platform-python to 3.6.8-51.el8_8.2|
| [CVE-2023-24329](https://access.redhat.com/errata/RHSA-2023:3595)|An issue in the urllib.parse component of Python before 3.11.4 allows attackers to bypass blocklisting methods by supplying a URL that starts with blank characters.|High|Upgrade python3-libs to 3.6.8-51.el8_8.1|
| [CVE-2023-40217](https://access.redhat.com/errata/RHSA-2023:5462)|An issue was discovered in Python before 3.8.18, 3.9.x before 3.9.18, 3.10.x before 3.10.13, and 3.11.x before 3.11.5. It primarily affects servers (such as HTTP servers) that use TLS client authentication. If a TLS server-side socket is created, receives data into the socket buffer, and then is closed quickly, there is a brief window where the SSLSocket instance will detect the socket as "not connected" and won't initiate a handshake, but buffered data will still be readable from the socket buffer. This data will not be authenticated if the server-side TLS peer is expecting client certificate authentication, and is indistinguishable from valid TLS stream data. Data is limited in size to the amount that will fit in the buffer. (The TLS connection cannot directly be used for data exfiltration because the vulnerable code path requires that the connection be closed on initialization of the SSLSocket.)|High|Upgrade python3-libs to 3.6.8-51.el8_8.2|
